[workspace]
package.version = "0.1.0"
package.edition = "2021"

members = ["program", "client/rust"]

[workspace.dependencies]
pinocchio = "0.8.1"
pinocchio-log = "0.4.0"
pinocchio-pubkey = "0.2.4"
pinocchio-system = "0.2.3"