[package]
name = "tower-defense-program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
pinocchio = "0.8.0"
pinocchio-log = "0.4.0"
pinocchio-pubkey = "0.2.4"
