[package]
name = "integration_tests"
version.workspace = true
edition.workspace = true

[dependencies]
td-program-sdk ={ path = "../client/rust"}

[dev-dependencies]
solana-program-test = "2.2.2"
solana-sdk = { workspace = true}
